// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Post struct {
	ID        sql.NullInt32
	Uuid      uuid.UUID
	Body      string
	ThreadID  int32
	CreatedAt time.Time
	UserID    int32
}

type Thread struct {
	ID        int32
	Uuid      uuid.UUID
	Topic     string
	CreatedAt time.Time
	UserID    int32
}

type User struct {
	ID        int32
	Uuid      uuid.UUID
	Username  string
	Password  string
	CreatedAt time.Time
}
